### PR TITLE
update kube api and dependencies to v0.19.0-rc.2

### PR DESCRIPTION
**Pull request by humblec**
Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

### CODE REVIEW

**Comment by humblec** [comment]
@xing-yang @msau42 @jsafrane ptal.

**Comment by humblec** [comment]
> @xing-yang @msau42 @jsafrane ptal.

`make all` successfully complete.

**Comment by xing-yang** [comment]
Can you take a look of the CI error?

**Comment by xing-yang** [comment]
The latest is v0.19.0-rc.2

**Comment by humblec** [comment]
> The latest is v0.19.0-rc.2

sure.. updated.

**Comment by humblec** [comment]
@xing-yang @msau42 @jsafrane ptal.. It was a flaky test I believe which caused the CI to fail.

**Pull request merged**
