### PR TITLE
Simplify storage class properties getters

### LINKED ISSUE #9: RFC: Simplify class properties getters
Currently, there are many private functions to retrieve properties of class:

- getStorageClassFields
- fetchReclaimPolicy
- fetchMountOptions
- fetchAllowedTopologies

This part of code has been duplicated many times: 

```go
    classObj, found, err := ctrl.classes.GetByKey(storageClassName)
    if err != nil {
        return nil, err
    }    
    if !found {
        return nil, fmt.Errorf("storageClass %q not found", storageClassName)
    }    

    switch class := classObj.(type) {
    case *storage.StorageClass:
        // action on *storage.StorageClass
    case *storagebeta.StorageClass:
        // action on *storagebeta.StorageClass
    } 
```

Actually, rest of function does not contain much logic code.

How about unify these into one function which just returns a `*storage.StorageClass` object with optional error? e.g. `getClass(name) (*storage.StorageClass, error)`

In this function, we can convert `*storagebeta.StorageClas` to `*storage.StorageClass` internally. Then, controller can act on one kind of storage class directly.

Alternatively, we can create a struct to contain all properties of class, but I don't think it is necessary, because storage.StorageClass includes all fields of *storagebeta.StorageClass.

### PR DESCRIPTION
**Pull request by cofyc**
fixes #9
And in `provisionClaimOperation`, we only need to get storage class once.

### CODE REVIEW

**Comment by wongma7** [comment]
lgtm, thank you @cofyc. sorry for the delay, now it needs a small rebase.

**Comment by cofyc** [comment]
@wongma7 rebased

**Comment by wongma7** [comment]
/lgtm
/approve
thanks again..much cleaner

**Pull request merged**
