### PR TITLE
Correctly detect selected node in K8s 1.11 cluster

### PR DESCRIPTION
**Pull request by tamalsaha**
Signed-off-by: Tamal Saha <tamal@appscode.com>

### CODE REVIEW

**Comment by tamalsaha** [comment]
I am looking to use this with OpenShift 3.11 cluster and https://github.com/rancher/local-path-provisioner

**Comment by jsafrane** [comment]
@wongma7, can you take a look please? No currently supported Kubernetes release uses the alpha annotation, yet the PR looks useful to me. But I am biased towards OpenShift :-).

**Pull request merged**
