### PR TITLE
Set provision-by anno to the storage class provisioner

### PR DESCRIPTION
**Pull request by Jiawei0227**
This PR changes the existing behavior of changing PV provisioned-by annotation to storageclass provisioner.

This is to help fix https://github.com/kubernetes-csi/external-provisioner/issues/576

Basically it means for CSI Migration, newly provisioned PV will have "provisioned-by" annotation set to in-tree provisioner name instead of the CSI provisioner.

### CODE REVIEW

**Comment by Jiawei0227** [comment]
/assign @jsafrane 

I am a little more concerned by this one because it seems to be a behavior change.
As we see from the def here: https://github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/blob/5fd51cfade8c066f42fc33300c3fe700b0f67cae/controller/controller.go#L74

The meaning of "pv.kubernetes.io/provisioned-by" is to actually tell the actual provisioner. I am less concerned if this lib is only being used by external-provisioner but it seems not. So I am wondering if this is a proper change to make.

**Comment by jsafrane** [comment]
I checked the rest of the library and you are probably correct, hardcoding `StorageClass.Provisioner` may be wrong. The library supports additional recognized provisioners:
https://github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/blob/5fd51cfade8c066f42fc33300c3fe700b0f67cae/controller/controller.go#L1137-L1146

If these `additionalProvisionerNames` are used, then there is indeed behavior change in this PR and the library will set wrong provisoner annotation.

Would it be possible to change the provisioner to in-tree only for migrated volume plugins, i.e. `StorageClass.Provisioner` is in-tree && migratable to CSI?

**Comment by Jiawei0227** [comment]
> Would it be possible to change the provisioner to in-tree only for migrated volume plugins, i.e. StorageClass.Provisioner is in-tree && migratable to CSI?
I guess it is possible. But is this okay? Do you know if the other controllers that are using this lib will have issues if we do something special to  in-tree and CSI?

**Comment by jsafrane** [comment]
If we do something special only for CSI migration, other users should be fine. However, currently the translation lib is not imported, so it can't do such a decision.

@wongma7, what do you think? So far we avoided importing the translation here.

At the same time I can see that additional provisioners were added exactly to support CSI migration. Does anyone use them outside of CSI external-provisioner? Would it be bad if we break those (and blindly set `pv.kubernetes.io/provisioned-by = storageSlass.Provisioner`?

**Comment by Jiawei0227** [comment]
Hey @wongma7 , any thoughts on this one?

**Comment by wongma7** [comment]
I am inclined to accept this PR and change the behavior for the benefit of external-provisioner CSI migration, we can bump the major version to signal the change in behavior. The impact should be minimal to zero, I don't think there exists any users passing AdditionalProvisionerNames to the controller anyway. https://github.com/search?q=AdditionalProvisionerNames&type=code

I strongly prefer it to importing migration lib and causing dependency headaches...
 
/lgtm

(sorry for being so late to this issue)

**Comment by wongma7** [comment]
/lgtm

( iresolved conflict using github web gui ..)

**Pull request merged**
