### PR TITLE
use context.Context in APIs

### PR DESCRIPTION
**Pull request by pohly**
Updating client-go to v1.18.0 was already an indirect API break for
sig-storage-lib-external-provisioner because consumers most likely had
to update their code when updating
sig-storage-lib-external-provisioner.

Instead of calling context.TODO in various leaf functions, a cleaner
solution is to expose that functions need a context and let callers
decide how they want to provide that.

For provisioning and deletion, timeouts can be configured separately
and then will be applied for all involved functions, including the
provisioner interface methods.

Consumers have been expected to switch ProvisioningExt for a
while. Now a single call with that same semantic and context is
required, i.e. ProvisionerExt gets merged into the normal Provisioner
interface.

### CODE REVIEW

**Comment by wongma7** [comment]
travis says:
/home/travis/gopath/src/sigs.k8s.io/sig-storage-lib-external-provisioner/examples/hostpath-provisioner/go.mod:10: require sigs.k8s.io/sig-storage-lib-external-provisioner/v6: version "v5.0.0" invalid: module contains a go.mod file, so major version must be compatible: should be v6, not v5

Now that this repo is using go.mod I don't think hostpath-provisioner also needs one? Unless we see value in there being an example go.mod for people starting a new project, which is rare, because they ought to be using CSI.

**Comment by pohly** [comment]
> travis says:
> /home/travis/gopath/src/sigs.k8s.io/sig-storage-lib-external-provisioner/examples/hostpath-provisioner/go.mod:10: require sigs.k8s.io/sig-storage-lib-external-provisioner/v6: version "v5.0.0" invalid: module contains a go.mod file, so major version must be compatible: should be v6, not v5

I had done a global `s;/v5;v6;` which missed the version number in the example go.mod. Fixed with:
```
diff --git a/examples/hostpath-provisioner/go.mod b/examples/hostpath-provisioner/go.mod
index eb26186..b5f2d47 100644
--- a/examples/hostpath-provisioner/go.mod
+++ b/examples/hostpath-provisioner/go.mod
@@ -7,7 +7,7 @@ require (
        k8s.io/apimachinery v0.18.0
        k8s.io/client-go v0.18.0
        k8s.io/klog v1.0.0
-       sigs.k8s.io/sig-storage-lib-external-provisioner/v6 v5.0.0
+       sigs.k8s.io/sig-storage-lib-external-provisioner/v6 v6.0.0
 )
```

> Now that this repo is using go.mod I don't think hostpath-provisioner also needs one?

Probably not. But that's worth a separate PR.

**Comment by pohly** [comment]
Looks like tests are a bit flaky? https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_sig-storage-lib-external-provisioner/79/pull-sig-storage-lib-external-provisioner-build/1275712415090085888 and https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_sig-storage-lib-external-provisioner/79/pull-sig-storage-lib-external-provisioner-unit/1275712415090085889 seem unrelated to this PR.

/retest

**Comment by pohly** [comment]
And of course the example source code needs to be adapted to the new API. Fixed. I hadn't noticed because "make" in the examples directory doesn't actually rebuild the binary if there is already one...

**Comment by pohly** [comment]
@wongma7 and/or @jsafrane : can this be merged now, followed by a v6.0.0 release shortly afterwards?

**Comment by wongma7** [comment]
/lgtm
/approve
Yes, will make a release

**Pull request merged**
