### PR TITLE
Migrate controller, utils, gidallocator from glog to klog

### PR DESCRIPTION
**Pull request by humblec**
Fix#77
Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

### CODE REVIEW

**Comment by humblec** [comment]
```
[root@localhost sig-storage-lib-external-provisioner]# make all
go mod tidy
# todo gometalinter is DEPRECATED, Use https://github.com/golangci/golangci-lint
GO111MODULE=off go get -u github.com/alecthomas/gometalinter
GO111MODULE=off gometalinter --install
....
sigs.k8s.io/sig-storage-lib-external-provisioner/v5/controller
sigs.k8s.io/sig-storage-lib-external-provisioner/v5/allocator
sigs.k8s.io/sig-storage-lib-external-provisioner/v5/controller
sigs.k8s.io/sig-storage-lib-external-provisioner/v5/mount
sigs.k8s.io/sig-storage-lib-external-provisioner/v5/repo-infra/verify/boilerplate/test
sigs.k8s.io/sig-storage-lib-external-provisioner/v5/v5/allocator
sigs.k8s.io/sig-storage-lib-external-provisioner/v5/v5/controller
sigs.k8s.io/sig-storage-lib-external-provisioner/v5/v5/controller/metrics
sigs.k8s.io/sig-storage-lib-external-provisioner/v5/v5/mount
sigs.k8s.io/sig-storage-lib-external-provisioner/v5/v5/util
sigs.k8s.io/sig-storage-lib-external-provisioner/v5/v5/gidallocator
sigs.k8s.io/sig-storage-lib-external-provisioner/v5/gidallocator
SUCCESS  /home/hchiramm/gopath/src/github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/repo-infra/verify/go-tools/verify-govet.sh	75s
repo-infra/verify/verify-boilerplate.sh
go test ./controller
ok  	sigs.k8s.io/sig-storage-lib-external-provisioner/v5/controller	13.779s
go test ./allocator
ok  	sigs.k8s.io/sig-storage-lib-external-provisioner/v5/allocator	0.002s
````

**Comment by humblec** [comment]
# todo gometalinter is DEPRECATED, Use https://github.com/golangci/golangci-lint
```
GO111MODULE=off go get -u github.com/alecthomas/gometalinter
GO111MODULE=off gometalinter --install
/bin/sh: 1: gometalinter: not found
make: *** [Makefile:23: verify] Error 127
```

**Comment by humblec** [comment]
@jsafrane looks like `gometalinter` installation and usage is broken in this repo CI for some time now :)

**Comment by msau42** [comment]
@humblec do you still plan to work on this?

**Comment by humblec** [comment]
@msau42 looks like I handled this in https://github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/commit/b1753123564037408f78e300faedcbbc82e50bdd .. so  closing this for now.

**Pull request closed without merging**
