### PR TITLE
Update to Kubernetes 1.30

### PR DESCRIPTION
**Pull request by jsafrane**
Update all Kubernetes libraries to 1.30 and go to 1.22. Fix our code accordingly (`v1.ResourceRequirements` -> `v1.VolumeResourceRequirements`.

When at it:
* Remove gometalinter usage. It has been deprecated and archived in 2019, it does not work with go 1.22. We don't use it in other storage repos either.
* Fix boilerplate check, `unittest.assertEquals` has been removed from Python  (3.12).

@xing-yang @msau42

### CODE REVIEW

**Comment by jsafrane** [comment]
I'm updating go version in https://github.com/kubernetes/test-infra/pull/32493

**Comment by xing-yang** [comment]
CI failed.

**Comment by jsafrane** [comment]
Damn, I need to install gometalinter in CI somehow. 

> /bin/sh: 1: gometalinter: not found

**Comment by jsafrane** [comment]
I removed the whole gometalinter, I did not make it work in go 1.22 easily and I don't think it's that useful either.

**Pull request merged**
