### PR TITLE
Lift kube dependency to v0.18.2

### PR DESCRIPTION
**Pull request by humblec**
Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

### CODE REVIEW

**Comment by humblec** [comment]
this is interesting :), locally make passes but here it fails with 
```
go: downloading github.com/fsnotify/fsnotify v1.4.7
go: extracting github.com/fsnotify/fsnotify v1.4.7
# todo gometalinter is DEPRECATED, Use https://github.com/golangci/golangci-lint
GO111MODULE=off go get -u github.com/alecthomas/gometalinter
GO111MODULE=off gometalinter --install
/bin/sh: 1: gometalinter: not found
make: *** [Makefile:23: verify] Error 127

```

**Comment by wongma7** [comment]
we are using. a super old version of https://github.com/kubernetes/repo-infra, the fix is to update our copy of it

**Comment by humblec** [comment]
closing in favor of #https://github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/pull/84

**Pull request closed without merging**
