### PR TITLE
Fix module path to include /v7 suffix

### PR DESCRIPTION
**Pull request by wongma7**
In https://github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/pull/108 I removed the symlink dir and also the /v6 suffix. We don't need the symlink dir anymore but we do need the suffix as explained at https://github.com/golang/go/wiki/Modules#semantic-import-versioning.

Otherwise packages trying to import us fail with:

go: errors parsing go.mod:
/home/ANT.AMAZON.COM/mattwon/go/src/github.com/kubernetes-csi/external-provisioner/go.mod:44:2: require sigs.k8s.io/sig-storage-lib-external-provisioner: version "v7.0.0" invalid: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v7

I'll release v7.0.1 after this.

### CODE REVIEW

**Comment by pohly** [comment]
The example probably also needs to be updated:
* https://github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/blob/4b6549bc87ee51837467b8122c62e6e3140bf7f5/examples/hostpath-provisioner/go.mod#L10
* https://github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/blob/4b6549bc87ee51837467b8122c62e6e3140bf7f5/examples/hostpath-provisioner/go.mod#L13
* https://github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/blob/4b6549bc87ee51837467b8122c62e6e3140bf7f5/examples/hostpath-provisioner/hostpath-provisioner.go#L27

**Comment by wongma7** [comment]
I updated the example and successfully ran its `go mod tidy` and built it

**Pull request merged**
