### PR TITLE
Release v7.0.0

### PR DESCRIPTION
**Pull request by wongma7**
Since dep was deprecated, I am not sure if the symlink pattern is still needed. @pohly do you know? thanks.

### CODE REVIEW

**Comment by pohly** [comment]
The symlinks shouldn't be needed anymore.

**Comment by pohly** [comment]
Why is the major version bump necessary?

**Comment by wongma7** [comment]
@pohly I'm removing an argument from NewProvisionController and there is a behavior change that while unlikely to break anybody si technically still breaking. details  on both changes: https://github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/issues/107

I'll submit a PR without the symlinks :+1: thanks.

**Pull request merged**
