### PR TITLE
Cleanup aliases to glog

### LINKED ISSUE #96: cleanup aliases to glog
There are areas of the code that aliased klog to glog because it would be too many lines to change. We should clean those up.

https://github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/blob/896be1e22d769b7f3e6d10a404b8323f0575ba82/controller/controller.go#L54

/help
/good-first-issue

### PR DESCRIPTION
**Pull request by Evalle**
PR Summary:
- cleans up aliases to glog
- Fixes #96 

FYI @msau42

### CODE REVIEW

**Comment by Evalle** [comment]
Also, @msau42 may I ask you to add  "hacktoberfest-accepted" label to this PR? If it's not a big issue, of course?

**Comment by msau42** [comment]
hmm I don't have permission to add the label. Maybe @jsafrane or @wongma7 can do it?

**Comment by msau42** [comment]
we may need #94 to merge first which updates klog to v2

**Comment by Evalle** [comment]
@msau42 this PR has been rebased to support the latest changes from https://github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/pull/94
I have created aliases like this:
```
klog "k8s.io/klog/v2"
```
Maybe I should replace them with 
```
klogv2 "k8s.io/klog/v2"
```
WDYT?

**Comment by msau42** [comment]
I prefer leaving it as klog so when there's a potential v3 in the future, we don't need to update all the references.

Thanks for working on this!
/lgtm

/assign @wongma7 @jsafrane

**Comment by wongma7** [comment]
/approve

tx

**Pull request merged**
