### PR TITLE
Migrate to klog from glog.

### PR DESCRIPTION
**Pull request by humblec**
Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

### CODE REVIEW

**Comment by humblec** [comment]
@wongma7 do I need to edit `.Gopkg.toml` as well ?

**Comment by humblec** [comment]
```
controller/controller.go:691:30:error: not enough arguments in call to resourcelock.New (vet)
controller/controller.go:691:30:error: not enough arguments in call to resourcelock.New (vet)
controller/controller.go:691:30:warning: not enough arguments in call to resourcelock.New (vetshadow)
controller/controller.go:691:30:warning: not enough arguments in call to resourcelock.New (vetshadow)
FAILED ```

Error is not related to this PR @wongma7

**Comment by jayunit100** [comment]
- I just saw this as well, the `resourcelock.New` you can get around with sending in nil as the contrroller type for compilation.  
- I tried editing the toml to secretly swap in k8s.klog as glog but it didnt seem to work, might look at that again today.

**Comment by humblec** [comment]
I think this PR can be closed.

**Pull request closed without merging**
