### PR TITLE
late binding: optionally avoid GET Node

### PR DESCRIPTION
**Pull request by pohly**
It may make sense to use an informer-based lister for Node instead of
doing a GET for each PVC with a selected node, in particular if there
is already a shared informer in the process.

Fixes: #99

/assign @verult

### CODE REVIEW

**Comment by wongma7** [comment]
/lgtm
/approve

TY

**Comment by pohly** [comment]
@wongma7 can you tag a v6.2.0 with this change?

**Comment by wongma7** [comment]
@pohly yes, done

**Pull request merged**
